#! /bin/bash
if ! [ -e ./zergmap ]
then
	make debug
fi
for x in $(ls mapper/pcaps); do
	echo $x
	valgrind ./zergmap mapper/pcaps/$x/* -h 25 2>&1 | grep -E '(total heap|ERROR SUMMARY)'
	echo ------------------------
	done;
